class FishRunner
{
	public static void main(String[] args)
	{
Fish fish=new Fish("star fish","big");
System.out.println("fish name:"+fish.name);
System.out.println("fish name:"+fish.size);
Fish fish1=new Fish("angle fish","small");
System.out.println("fish name:"+fish1.name);
System.out.println("fish name:"+fish1.size);
Fish fish2=new Fish("hagfish","small");
System.out.println("fish name:"+fish2.name);
System.out.println("fish name:"+fish2.size);
Fish fish3=new Fish("lampreys","larger");
System.out.println("fish name:"+fish3.name);
System.out.println("fish name:"+fish3.size);
Fish fish4=new Fish("cartilaginous fish","large");
System.out.println("fish name:"+fish4.name);
System.out.println("fish name:"+fish4.size);
Fish fish5=new Fish("ray-finned fish","small");
System.out.println("fish name:"+fish5.name);
System.out.println("fish name:"+fish5.size);
Fish fish6=new Fish("lobe-finned fish","big");
System.out.println("fish name:"+fish6.name);
System.out.println("fish name:"+fish6.size);
Fish fish7=new Fish("Goldfish","small");
System.out.println("fish name:"+fish7.name);
System.out.println("fish name:"+fish7.size);
Fish fish8=new Fish("Betta Fish","medium");
System.out.println("fish name:"+fish8.name);
System.out.println("fish name:"+fish8.size);
Fish fish9=new Fish("Guppies","small");
System.out.println("fish name:"+fish9.name);
System.out.println("fish name:"+fish9.size);
Fish fish10=new Fish("Clownfish","big");
System.out.println("fish name:"+fish10.name);
System.out.println("fish name:"+fish10.size);



Lamp lamp1=new Lamp("pink",10.9);
System.out.println("Lamp:"+lamp1.color);
System.out.println("Lamp:"+lamp1.price);
Lamp lamp2=new Lamp("red",20.9);
System.out.println("Lamp:"+lamp2.color);
System.out.println("Lamp"+lamp2.price);
Lamp lamp3=new Lamp("green",30.9);
System.out.println("Lamp:"+lamp3.color);
System.out.println("Lamp:"+lamp3.price);
Lamp lamp4=new Lamp("pink",30.9);
System.out.println("Lamp:"+lamp4.color);
System.out.println("Lamp:"+lamp4.price);
Lamp lamp5=new Lamp("black",40.9);
System.out.println("Lamp:"+lamp5.color);
System.out.println("Lamp:"+lamp5.price);
Lamp lamp6=new Lamp("white",70.9);
System.out.println("Lamp:"+lamp6.color);
System.out.println("Lamp:"+lamp6.price);
Lamp lamp7=new Lamp("black",72.9);
System.out.println("Lamp:"+lamp7.color);
System.out.println("fish name:"+lamp7.price);
Lamp lamp8=new Lamp("blue",73.9);
System.out.println("Lamp:"+lamp8.color);
System.out.println("Lamp:"+lamp8.price);
Lamp lamp9=new Lamp("purple",12.9);
System.out.println("Lamp:"+lamp9.color);
System.out.println("Lamp:"+lamp9.price);
Lamp lamp10=new Lamp("green",92.9);
System.out.println("Lamp:"+lamp10.color);
System.out.println("Lamp:"+lamp10.price);
Lamp lamp=new Lamp("red",93.9);
System.out.println("Lamp:"+lamp.color);
System.out.println("Lamp:"+lamp.price);


PrintingMachine printingMachine=new PrintingMachine(11000,"black");
System.out.println("PrintingMachine:"+printingMachine.price);
System.out.println("PrintingMachine:"+printingMachine.color);
PrintingMachine printingMachine1=new PrintingMachine(1000,"black");
System.out.println("PrintingMachine:"+printingMachine1.price);
System.out.println("PrintingMachine:"+printingMachine1.color);
PrintingMachine printingMachine2=new PrintingMachine(2000,"black");
System.out.println("PrintingMachine:"+printingMachine2.price);
System.out.println("PrintingMachine:"+printingMachine2.color);
PrintingMachine printingMachine3=new PrintingMachine(3000,"black");
System.out.println("PrintingMachine:"+printingMachine3.price);
System.out.println("PrintingMachine:"+printingMachine3.color);
PrintingMachine printingMachine4=new PrintingMachine(4000,"black");
System.out.println("PrintingMachine:"+printingMachine4.price);
System.out.println("PrintingMachine:"+printingMachine4.color);
PrintingMachine printingMachine5=new PrintingMachine(5000,"black");
System.out.println("PrintingMachine:"+printingMachine5.price);
System.out.println("PrintingMachine:"+printingMachine5.color);
PrintingMachine printingMachine6=new PrintingMachine(6000,"black");
System.out.println("PrintingMachine:"+printingMachine6.price);
System.out.println("PrintingMachine:"+printingMachine6.color);
PrintingMachine printingMachine7=new PrintingMachine(7000,"black");
System.out.println("PrintingMachine:"+printingMachine7.price);
System.out.println("PrintingMachine:"+printingMachine7.color);
PrintingMachine printingMachine8=new PrintingMachine(8000,"black");
System.out.println("PrintingMachine:"+printingMachine8.price);
System.out.println("PrintingMachine:"+printingMachine8.color);
PrintingMachine printingMachine9=new PrintingMachine(9000,"black");
System.out.println("PrintingMachine:"+printingMachine9.price);
System.out.println("PrintingMachine:"+printingMachine9.color);
PrintingMachine printingMachine10=new PrintingMachine(10000,"black");
System.out.println("PrintingMachine:"+printingMachine10.price);
System.out.println("PrintingMachine"+printingMachine10.color);

Lens lens=new Lens("lenscart",'s');
System.out.println("Lens:"+lens.brand);
System.out.println("Lens:"+lens.size);
Lens lens1=new Lens("Essilor",'x');
System.out.println("Lens:"+lens1.brand);
System.out.println("Lens:"+lens1.size);
Lens lens2=new Lens("Hoya",'M');
System.out.println("Lens:"+lens2.brand);
System.out.println("Lens:"+lens2.size);
Lens lens3=new Lens("Nikon",'s');
System.out.println("Lens:"+lens3.brand);
System.out.println("Lens:"+lens3.size);
Lens lens4=new Lens("Norville",'x');
System.out.println("Lens:"+lens4.brand);
System.out.println("Lens:"+lens4.size);
Lens lens5=new Lens("Rodenstock",'m');
System.out.println("Lens:"+lens5.brand);
System.out.println("Lens:"+lens5.size);
Lens lens6=new Lens("Seiko",'s');
System.out.println("Lens:"+lens6.brand);
System.out.println("Lens:"+lens6.size);
Lens lens7=new Lens("Shamir",'x');
System.out.println("Lens:"+lens7.brand);
System.out.println("Lens:"+lens7.size);
Lens lens8=new Lens("Zeiss",'L');
System.out.println("Lens:"+lens8.brand);
System.out.println("Lens:"+lens8.size);
Lens lens9=new Lens("Johnson",'s');
System.out.println("Lens:"+lens9.brand);
System.out.println("Lens:"+lens9.size);
Lens lens10=new Lens("Ciba Vision",'x');
System.out.println("Lens:"+lens10.brand);
System.out.println("Lens:"+lens10.size);

Coil coil=new Coil(100,"allout");
System.out.println("coil price:"+coil.cost);
System.out.println("coil price:"+coil.brand);
Coil coil1=new Coil(10,"goodnight");
System.out.println("coil price:"+coil1.cost);
System.out.println("coil price:"+coil1.brand);
Coil coil2=new Coil(20,"allout");
System.out.println("coil price:"+coil2.cost);
System.out.println("coil price:"+coil2.brand);
Coil coil3=new Coil(30,"allout");
System.out.println("coil price:"+coil3.cost);
System.out.println("coil price:"+coil3.brand);
Coil coil4=new Coil(50,"goodnight");
System.out.println("coil price:"+coil4.cost);
System.out.println("coil price:"+coil4.brand);
Coil coil5=new Coil(90,"allout");
System.out.println("coil price:"+coil5.cost);
System.out.println("coil price:"+coil5.brand);
Coil coil6=new Coil(60,"allout");
System.out.println("coil price:"+coil6.cost);
System.out.println("coil price:"+coil6.brand);
Coil coil7=new Coil(70,"goodnight");
System.out.println("coil price:"+coil7.cost);
System.out.println("coil price:"+coil7.brand);
Coil coil8=new Coil(80,"allout");
System.out.println("coil price:"+coil8.cost);
System.out.println("coil brand:"+coil8.brand);
Coil coil9=new Coil(20,"goodnight");
System.out.println("coil price:"+coil9.cost);
System.out.println("coil price:"+coil9.brand);
Coil coil10=new Coil(110,"allout");
System.out.println("coil price:"+coil10.cost);
System.out.println("coil brand:"+coil10.brand);

Cap cap=new Cap('s',50,"dark blue");
System.out.println("cap size:"+cap.size);
System.out.println("cap price:"+cap.price);
System.out.println("cap size:"+cap.color);
Cap cap1=new Cap('x',30,"yellow");
System.out.println("cap size:"+cap1.size);
System.out.println("cap price:"+cap1.price);
System.out.println("cap size:"+cap1.color);
Cap cap2=new Cap('s',50,"orange");
System.out.println("cap size:"+cap2.size);
System.out.println("cap price:"+cap2.price);
System.out.println("cap size:"+cap2.color);
Cap cap3=new Cap('M',100,"voilate");
System.out.println("cap size:"+cap3.size);
System.out.println("cap price:"+cap3.price);
System.out.println("cap size:"+cap3.color);
Cap cap4=new Cap('s',300,"pink");
System.out.println("cap size:"+cap4.size);
System.out.println("cap price:"+cap4.price);
System.out.println("cap size:"+cap4.color);
Cap cap5=new Cap('s',50,"indigo");
System.out.println("cap size:"+cap5.size);
System.out.println("cap price:"+cap5.price);
System.out.println("cap size:"+cap5.color);
Cap cap6=new Cap('x',60,"black");
System.out.println("cap size:"+cap6.size);
System.out.println("cap price:"+cap6.price);
System.out.println("cap size:"+cap6.color);
Cap cap7=new Cap('x',70,"brown");
System.out.println("cap size:"+cap7.size);
System.out.println("cap price:"+cap7.price);
System.out.println("cap size:"+cap7.color);
Cap cap8=new Cap('S',500,"navy blue");
System.out.println("cap size:"+cap8.size);
System.out.println("cap price:"+cap8.price);
System.out.println("cap size:"+cap8.color);
Cap cap9=new Cap('M',50,"red");
System.out.println("cap size:"+cap9.size);
System.out.println("cap price:"+cap9.price);
System.out.println("cap size:"+cap9.color);
Cap cap10=new Cap('L',50,"grey");
System.out.println("cap size:"+cap10.size);
System.out.println("cap price:"+cap10.price);
System.out.println("cap size:"+cap10.color);


Gold gold=new Gold(100000,"malabar gold","biscuit");
System.out.println("gold price:"+gold.price);
System.out.println("gold brand:"+gold.brand);
System.out.println("gold shape:"+gold.shape);
Gold gold1=new Gold(50000,"Tanisq","square");
System.out.println("gold price:"+gold1.price);
System.out.println("gold brand:"+gold1.brand);
System.out.println("gold shape:"+gold1.shape);
Gold gold2=new Gold(60000,"malleshwaram","circle");
System.out.println("gold price:"+gold2.price);
System.out.println("gold brand:"+gold2.brand);
System.out.println("gold shape:"+gold2.shape);
Gold gold3=new Gold(70000,"kalyan jewelers","biscuits");
System.out.println("gold price:"+gold3.price);
System.out.println("gold brand:"+gold3.brand);
System.out.println("gold shape:"+gold3.shape);
Gold gold4=new Gold(30000,"dion","sqaure");
System.out.println("gold price:"+gold4.price);
System.out.println("gold brand:"+gold4.brand);
System.out.println("gold shape:"+gold4.shape);
Gold gold5=new Gold(100000,"rajesh","circle");
System.out.println("gold price:"+gold5.price);
System.out.println("gold brand:"+gold5.brand);
System.out.println("gold shape:"+gold5.shape);
Gold gold6=new Gold(500000,"titan","biscuit");
System.out.println("gold price:"+gold6.price);
System.out.println("gold brand:"+gold6.brand);
System.out.println("gold shape:"+gold6.shape);
Gold gold7=new Gold(60000,"dion","circle");
System.out.println("gold price:"+gold7.price);
System.out.println("gold brand:"+gold7.brand);
System.out.println("gold shape:"+gold7.shape);
Gold gold8=new Gold(70000,"vaneck","square");
System.out.println("gold price:"+gold8.price);
System.out.println("gold brand:"+gold8.brand);
System.out.println("gold shape:"+gold8.shape);
Gold gold9=new Gold(60000,"Joyalukkas","biscuit");
System.out.println("gold price:"+gold9.price);
System.out.println("gold brand:"+gold9.brand);
System.out.println("gold shape:"+gold9.shape);
Gold gold10=new Gold(50000,"Senco Gold","circle");
System.out.println("gold price:"+gold10.price);
System.out.println("gold brand:"+gold10.brand);
System.out.println("gold shape:"+gold10.shape);


Board board=new Board("pink",24,12);
System.out.println("board color:"+board.color);
System.out.println("board length:"+board.length);
System.out.println("board width:"+board.width);
Board board1=new Board("red",20,14);
System.out.println("board color:"+board1.color);
System.out.println("board length:"+board1.length);
System.out.println("board width:"+board1.width);
Board board2=new Board("orange",75,34);
System.out.println("board color:"+board2.color);
System.out.println("board length:"+board2.length);
System.out.println("board width:"+board2.width);
Board board3=new Board("white",56,43);
System.out.println("board color:"+board3.color);
System.out.println("board length:"+board3.length);
System.out.println("board width:"+board3.width);
Board board4=new Board("purple",67,12);
System.out.println("board color:"+board4.color);
System.out.println("board length:"+board4.length);
System.out.println("board width:"+board4.width);
Board board5=new Board("blue",67,23);
System.out.println("board color:"+board5.color);
System.out.println("board length:"+board5.length);
System.out.println("board width:"+board5.width);
Board board6=new Board("black",56,67);
System.out.println("board color:"+board6.color);
System.out.println("board length:"+board6.length);
System.out.println("board width:"+board6.width);
Board board7=new Board("white",67,43);
System.out.println("board color:"+board7.color);
System.out.println("board length:"+board7.length);
System.out.println("board width:"+board7.width);
Board board8=new Board("blue",78,56);
System.out.println("board color:"+board8.color);
System.out.println("board length:"+board8.length);
System.out.println("board width:"+board8.width);
Board board9=new Board("green",78,23);
System.out.println("board color:"+board9.color);
System.out.println("board length:"+board9.length);
System.out.println("board width:"+board9.width);
Board board10=new Board("pink",67,89);
System.out.println("board color:"+board10.color);
System.out.println("board length:"+board10.length);
System.out.println("board width:"+board10.width);

Led led=new Led(20,"Standard LED","pink");
System.out.println("led price:"+led.price);
System.out.println("led name:"+led.name);
System.out.println("led color:"+led.color);
Led led1=new Led(30,"Miniature LED","red");
System.out.println("led price:"+led1.price);
System.out.println("led name:"+led1.name);
System.out.println("led color:"+led1.color);
Led led2=new Led(10,"High-Power LED","orange");
System.out.println("led price:"+led2.price);
System.out.println("led name:"+led2.name);
System.out.println("led color:"+led2.color);
Led led3=new Led(50,"RGB","white");
System.out.println("led price:"+led3.price);
System.out.println("led name:"+led3.name);
System.out.println("led color:"+led3.color);
Led led4=new Led(89,"Bi-color","purple");
System.out.println("led price:"+led4.price);
System.out.println("led name:"+led4.name);
System.out.println("led color:"+led4.color);
Led led5=new Led(12,"Flashing","blue");
System.out.println("led price:"+led5.price);
System.out.println("led name:"+led5.name);
System.out.println("led color:"+led5.color);
Led led6=new Led(5,"Infrared LED","black");
System.out.println("led price:"+led6.price);
System.out.println("led name:"+led6.name);
System.out.println("led color:"+led6.color);
Led led7=new Led(20,"Ultraviolet LED","white");
System.out.println("led price:"+led7.price);
System.out.println("led name:"+led7.name);
System.out.println("led color:"+led7.color);
Led led8=new Led(100,"MicroLED","green");
System.out.println("led price:"+led8.price);
System.out.println("led name:"+led8.name);
System.out.println("led color:"+led8.color);
Led led9=new Led(200,"COB","pink");
System.out.println("led price:"+led9.price);
System.out.println("led name:"+led9.name);
System.out.println("led color:"+led9.color);
Led led10=new Led(45,"Filament LED","pink");
System.out.println("led price:"+led10.price);
System.out.println("led name:"+led10.name);
System.out.println("led color:"+led10.color);

SimCard simcard=new SimCard("airtel",300,"64GB");
System.out.println("simcard brand:"+simcard.brand);
System.out.println("simcard price:"+simcard.price);
System.out.println("simcard storage:"+simcard.storage);
SimCard simcard1=new SimCard("Jio",400,"32GB");
System.out.println("simcard brand:"+simcard1.brand);
System.out.println("simcard price:"+simcard1.price);
System.out.println("simcard storage:"+simcard1.storage);
SimCard simcard2=new SimCard("BSNL",200,"64GB");
System.out.println("simcard brand:"+simcard2.brand);
System.out.println("simcard price:"+simcard2.price);
System.out.println("simcard storage:"+simcard2.storage);
SimCard simcard3=new SimCard("Vodafone Idea Limited",500,"12GB");
System.out.println("simcard brand:"+simcard3.brand);
System.out.println("simcard price:"+simcard3.price);
System.out.println("simcard storage:"+simcard3.storage);
SimCard simcard4=new SimCard("MTNL",400,"64GB");
System.out.println("simcard brand:"+simcard4.brand);
System.out.println("simcard price:"+simcard4.price);
System.out.println("simcard storage:"+simcard4.storage);
SimCard simcard5=new SimCard("Vodafone Idea",700,"32GB");
System.out.println("simcard brand:"+simcard5.brand);
System.out.println("simcard price:"+simcard5.price);
System.out.println("simcard storage:"+simcard5.storage);
SimCard simcard6=new SimCard("vi",800,"8GB");
System.out.println("simcard brand:"+simcard6.brand);
System.out.println("simcard price:"+simcard6.price);
System.out.println("simcard storage:"+simcard6.storage);
SimCard simcard7=new SimCard("Verizon",200,"72GB");
System.out.println("simcard brand:"+simcard7.brand);
System.out.println("simcard price:"+simcard7.price);
System.out.println("simcard storage:"+simcard7.storage);
SimCard simcard8=new SimCard("Postpaid",100,"32GB");
System.out.println("simcard brand:"+simcard8.brand);
System.out.println("simcard price:"+simcard8.price);
System.out.println("simcard storage:"+simcard8.storage);
SimCard simcard9=new SimCard("Quadrant",600,"16GB");
System.out.println("simcard brand:"+simcard9.brand);
System.out.println("simcard price:"+simcard9.price);
System.out.println("simcard storage:"+simcard9.storage);
SimCard simcard10=new SimCard("RCom",500,"64GB");
System.out.println("simcard brand:"+simcard10.brand);
System.out.println("simcard price:"+simcard10.price);
System.out.println("simcard storage:"+simcard10.storage);
	}
}